# Generated by Django 3.0.8 on 2020-08-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Branch',
            field=models.CharField(choices=[('ECE', 'ece'), ('CSE', 'cse'), ('IT', 'it'), ('EEE', 'eee')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
