# Generated by Django 3.0.8 on 2020-08-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=50)),
                ('hero', models.CharField(max_length=50)),
                ('heroin', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('poster', models.ImageField(null=True, upload_to='poster/')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
