# Generated by Django 3.0.8 on 2020-08-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Number', models.IntegerField()),
                ('Book_Name', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=30)),
                ('Department', models.CharField(choices=[('ece', 'ECE'), ('cse', 'CSE'), ('it', 'IT'), ('mech', 'MECH'), ('civil', 'CIVIL'), ('chem', 'CHEM')], max_length=20)),
                ('Publication_Date', models.DateField()),
            ],
        ),
    ]
