# Generated by Django 3.0.8 on 2020-08-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='Publication_Date',
            field=models.CharField(max_length=30),
        ),
    ]
